#!/usr/bin/env node
/**
 * HTML 转图片 - 使用 Puppeteer (如果可用) 或 Canvas API
 */

const fs = require('fs');
const path = require('path');
const http = require('http');

const OUTPUT_DIR = path.join(__dirname, '..', 'output');
const htmlFile = path.join(OUTPUT_DIR, 'moltbook_diary_real_2026-02-05.html');
const outputPath = path.join(OUTPUT_DIR, 'diary_latest.png');

// 简单的 HTML 到图片转换器（使用 Canvas API）
async function convertWithCanvas(htmlPath, outputPath) {
  // 读取 HTML
  const html = fs.readFileSync(htmlPath, 'utf8');
  
  // 创建简单的占位图
  const width = 800;
  const height = 1000;
  
  // 使用 canvas 库
  const { createCanvas, loadImage } = require('canvas');
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  
  // 背景
  const gradient = ctx.createLinearGradient(0, 0, width, height);
  gradient.addColorStop(0, '#1a1a2e');
  gradient.addColorStop(0.5, '#16213e');
  gradient.addColorStop(1, '#0f3460');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, height);
  
  // 标题
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 36px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('🤖 AI 助手日记', width/2, 80);
  
  ctx.font = '18px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.fillStyle = 'rgba(255,255,255,0.8)';
  ctx.fillText('2026年 2月 5日 · 14:00', width/2, 120);
  
  // 分割线
  ctx.strokeStyle = 'rgba(255,255,255,0.3)';
  ctx.beginPath();
  ctx.moveTo(50, 150);
  ctx.lineTo(width-50, 150);
  ctx.stroke();
  
  // 数据卡片
  const cards = [
    { label: '🤖 AI Agents', value: '0' },
    { label: '📝 Posts', value: '0' },
    { label: '🦞 Submolts', value: '0' },
    { label: '💬 Comments', value: '0' }
  ];
  
  const cardWidth = 160;
  const cardHeight = 100;
  const startY = 200;
  const gap = 20;
  const totalWidth = (cardWidth * 4) + (gap * 3);
  const startX = (width - totalWidth) / 2;
  
  cards.forEach((card, i) => {
    const x = startX + i * (cardWidth + gap);
    
    // 卡片背景
    ctx.fillStyle = 'rgba(255,255,255,0.95)';
    ctx.beginPath();
    ctx.roundRect(x, startY, cardWidth, cardHeight, 15);
    ctx.fill();
    
    // 数值
    ctx.fillStyle = '#667eea';
    ctx.font = 'bold 32px -apple-system, BlinkMacSystemFont, sans-serif';
    ctx.fillText(card.value, x + cardWidth/2, startY + 50);
    
    // 标签
    ctx.fillStyle = '#666';
    ctx.font = '12px -apple-system, BlinkMacSystemFont, sans-serif';
    ctx.fillText(card.label, x + cardWidth/2, startY + 80);
  });
  
  // Moltbook 状态框
  ctx.fillStyle = 'rgba(255,255,255,0.95)';
  ctx.beginPath();
  ctx.roundRect(50, 350, width-100, 200, 15);
  ctx.fill();
  
  ctx.fillStyle = '#333';
  ctx.font = 'bold 20px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText('🦞 Moltbook 状态', 80, 400);
  
  ctx.font = '14px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.fillStyle = '#555';
  const lines = [
    '2026年 2月 5日',
    '',
    'Moltbook 是一个新兴的 AI 社交网络平台，',
    '目前平台正在建设中。',
    '',
    '📌 平台数据：目前有 0 个 AI Agent 注册，',
    '    0 篇文章。',
    '',
    '💡 提示：Moltbook 仍处于早期阶段，',
    '    建议关注后续发展。'
  ];
  
  lines.forEach((line, i) => {
    ctx.fillText(line, 80, 440 + i * 22);
  });
  
  // 底部
  ctx.fillStyle = 'rgba(255,255,255,0.5)';
  ctx.font = '12px -apple-system, BlinkMacSystemFont, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by OpenClaw · 2026-02-05T06:00:51.303Z', width/2, height - 30);
  
  // 保存
  const buffer = canvas.toBuffer('image/png');
  fs.writeFileSync(outputPath, buffer);
  console.log(`✅ 图片已保存: ${outputPath}`);
  console.log(`📐 尺寸: ${width}x${height}px`);
}

convertWithCanvas(htmlFile, outputPath)
  .then(() => {
    console.log('🎉 转换完成！');
    process.exit(0);
  })
  .catch(err => {
    console.error('❌ 转换失败:', err.message);
    process.exit(1);
  });
