#!/usr/bin/env node
/**
 * Trading Signal System
 * 自动生成交易信号并发送到 Telegram
 */

const fs = require('fs');
const path = require('path');

const BOT_LOG = path.join(__dirname, '../okx-grid-bot/bot.log');
const SIGNAL_FILE = path.join(__dirname, '../okx-grid-bot/last-signal.json');

// 获取最新交易
function getLatestTrade() {
    try {
        const log = fs.readFileSync(BOT_LOG, 'utf8');
        const lines = log.split('\n');
        
        for (let i = lines.length - 1; i >= 0; i--) {
            const line = lines[i];
            if (line.includes('💰') && (line.includes('buy') || line.includes('sell'))) {
                const priceMatch = line.match(/@ ([\d.]+)/);
                const actionMatch = line.match(/(buy|sell)/);
                const timeMatch = line.match(/\[(.*?)\]/);
                
                if (priceMatch && actionMatch) {
                    return {
                        price: parseFloat(priceMatch[1]),
                        action: actionMatch[1],
                        time: timeMatch ? timeMatch[1] : ''
                    };
                }
            }
        }
    } catch (e) {}
    return null;
}

// 加载上次信号
function loadLastSignal() {
    try {
        if (fs.existsSync(SIGNAL_FILE)) {
            return JSON.parse(fs.readFileSync(SIGNAL_FILE, 'utf8'));
        }
    } catch (e) {}
    return { action: '', price: 0, time: '' };
}

function saveSignal(signal) {
    fs.writeFileSync(SIGNAL_FILE, JSON.stringify(signal, null, 2));
}

// 生成信号消息
function generateSignalMessage(trade, btcPrice) {
    const emoji = trade.action === 'buy' ? '🟢' : '🔴';
    const action = trade.action === 'buy' ? '买入' : '卖出';
    
    return `
${emoji} **BTC 交易信号**

**操作:** ${action}
**价格:** $${trade.price}
**BTC现价:** $${btcPrice}

---
*Generated by THEMACHINE Corp.*
`;
}

// 主函数
async function main() {
    console.log('=== Trading Signal Check ===');
    
    const trade = getLatestTrade();
    if (!trade) {
        console.log('No recent trade found');
        return;
    }
    
    const lastSignal = loadLastSignal();
    
    // 检查是否有新交易
    if (trade.action !== lastSignal.action || trade.price !== lastSignal.price) {
        console.log(`New signal: ${trade.action} @ $${trade.price}`);
        
        // 保存新信号
        saveSignal({
            action: trade.action,
            price: trade.price,
            time: new Date().toISOString()
        });
        
        // 生成消息
        const message = generateSignalMessage(trade, 64500); // 简化处理
        console.log(message);
        
        // TODO: 发送到 Telegram
        // 需要配置 Telegram Bot
    } else {
        console.log('No new signal');
    }
}

main().catch(console.error);
