const esbuild = require('esbuild');
const path = require('path');

async function build() {
  try {
    await esbuild.build({
      entryPoints: [path.join(__dirname, 'auth.ts')],
      bundle: true,
      outfile: path.join(__dirname, 'auth.bundle.js'),
      format: 'esm',
      platform: 'browser',
      target: ['es2020'],
      sourcemap: true,
      minify: process.env.NODE_ENV === 'production',
      banner: {
        js: '// Generated by esbuild - bcryptjs bundled'
      }
    });
    console.log('✅ Build complete: auth.bundle.js');
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

build();
